### ISSUE TITLE
Chaining IPs in x-forwarded-for

### ISSUE THREAD

**Issue by sander-oxbio** [wi1dcard/fingerproxy#22]
When a HTTP request is made through a proxy, eg in a corporate network, the fingerproxy replaces the existing x-forwarded-for with its own IP address. This should be copying the header fromthe inbound request before calling SetXForwarded. An example is given at URL: pkg.go.dev/net/http/httputil

**Comment by wi1dcard** [comment]
I didn't get the idea using fingerproxy behind another HTTP proxy. It should be deployed at the edge to collect fingerprints of clients. Can you explain some meaningful use cases?

**Comment by sander-oxbio** [comment]
Sure,
Use case: a browser is located in a corporate network and communicates to the Internet through a TLS termination proxy, which will look at the data in/out the company and if passed muster will again TLS the request and send it to the real URL. The fingerproxy will only see the TLS handshake of the termination proxy. That fingerprint doesn't match regular browser fingerprints. If the IPs in the existing x-forwarded-for header are added then you'll know an extra TLS termination proxy was between the browser and the fingerproxy. Most proxies especially corporate ones will add this header and thus in such a case you can expect non-browser fingerprints. The goal is to lower false positives by knowing which TLS fingerprint belongs to a TLS termination proxy, e.g. Blue Coat, Fortigate, Zscaler

**Comment by wi1dcard** [comment]
That makes sense. Thank you. Soon later a new release will be published.
